# config.yaml
simple_llama_studio:
  # ---------------------------------------------------------
  # base_path: プロジェクトのルートディレクトリ
  # ※通常は自動取得されるため、この項目は記述不要です。
  # ---------------------------------------------------------
  models_path: "models"
  
